main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Uxzylon
description: Place Satelite Map
commands:
  satmap:
    description: Place Satelite Map
    usage: /<command> <function>
    permission: satmap.command
permissions:
  satmap.command.load:
    description: Load Satelite Map
    default: op
    children:
      satmap.command: true
  satmap.command.place:
    description: Place Satelite Map
    default: op
    children:
      satmap.command: true
  satmap.command.reload:
    description: Reload Satelite Map
    default: op
    children:
      satmap.command: true
  satmap.*:
    description: Grants all other permissions
    default: false
    children:
      satmap.command: true
  satmap.command.*:
    description: Grants all permissions for commands
    default: false
    children:
      satmap.command.place: true
      satmap.command.load: true
      satmap.command.reload: true
